/**
 * Emits the SQL seed for public.map_objects from the same generator the client uses,
 * so the database picks hidden objects from exactly the props that exist in the world.
 *
 * Usage: npm run seed:map
 */
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { generateMap } from '../src/game/map/generateMap'
import { MAP_SEED } from '../src/game/map/constants'

const map = generateMap(MAP_SEED)

const rows = map.props
  .map((p) => `  ('${p.id}', '${p.kind}', ${p.x}, ${p.z}, ${p.weight})`)
  .join(',\n')

const sql = `-- Generated by scripts/generate-map-seed.ts for map seed ${MAP_SEED}. Do not edit by hand.
delete from public.map_objects;
insert into public.map_objects (id, kind, x, z, weight) values
${rows};
`

const target = resolve(process.cwd(), 'supabase/migrations/0004_seed_map_objects.sql')
writeFileSync(target, sql)
console.log(`Wrote ${map.props.length} map objects to ${target}`)
